name: test

on: [push]
jobs:
  test:
    #run location
    runs-on: ubuntu-latest
    #what does
    steps:
        #get repository
      - uses: actions/checkout@v3
        #configuring java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          #run tests
      - run: ./gradwlew clean test